### ISSUE TITLE
Скачивание файлов из доп полей товара

### ISSUE THREAD

**Issue by yehhor** [wmakeev/moysklad#5]
Добрый день!
Очень полезная библиотека, много времени сэкономил, спасибо большое что занимаетесь развитием этого дела!
Не могли бы вы помочь, не могу разобраться как формировать ссылку на скачивание файла который лежит в доп поле товара 
```
product = {
...params,
 attributes: [

        {
            "id" : "3333",
            "name" : "Документация 1",
            "value" : "ремонт"
        },
  ]
}
```

- на странице товара это отображается как файл.
документация совсем не дает понимания
https://online.moysklad.ru/api/remap/1.1/doc#header-ссылки-на-файлы вот этим пунктом.

Спасибо!

**Comment by wmakeev** [comment]
@yehhor не совсем понятен вопрос. Нужен пример для js?
Ссылка для скачивания в поле атрибута `product.attributes[].download.href`.

**Comment by wmakeev** [comment]
Думаю, сложность у вас возникла в том, что файл не скачивается напрямую, а через 307 редирект.

Ниже пример кода, который загружает файл в атрибуте в папку проекта в файл `attachment.json`

```js
'use strict'

require('dotenv').config()

const fs = require('fs')
const path = require('path')
const Moysklad = require('moysklad')
const nodeFetch = require('node-fetch')

const PRODUCT_ID = '2b461f14-0c41-48d2-bdd8-d6f8b36dfab8'
const PRODUCT_ATTR_ID = 'c42c741f-33e1-11e6-7a69-8f550011e952'

async function main () {
    const ms = Moysklad({ fetch: nodeFetch })

    // Загружаем товар
    let product = await ms.GET(['entity/product', PRODUCT_ID])

    // Достаем атрибут с вложенным файлом
    let attr = product.attributes.find(a => a.id === PRODUCT_ATTR_ID)

    // Получаем ссылку на файл (с авторизацией)
    let resp1 = await nodeFetch(attr.download.href, {
        headers: {
            'Authorization': ms.getAuthHeader()
        },
        redirect: 'manual'
    })

    let fileUrl = resp1.headers.get('location')

    // Загружаем файл (без авторизации)
    let resp2 = await nodeFetch(fileUrl)

    // Создаем поток для записи файла на диск
    let writeStream = fs.createWriteStream(path.join(__dirname, 'attachment.json'))

    // Пишем содержимое файла на диск
    resp2.body.pipe(writeStream)
}

main()
```

В дальнейшем я подумаю над тем как можно подобные задачи решить сразу через библиотеку без лишнего кода на получение ссылки и загрузку файла.
