### ISSUE TITLE
Параметр для отключения вебхука в контексте запроса

### ISSUE THREAD

**Issue by crystalbit** [wmakeev/moysklad#6]
Большое спасибо за библиотеку :)

Из апи 1.1:
```
ЗАГОЛОВОК ВРЕМЕННОГО ОТКЛЮЧЕНИЯ ЧЕРЕЗ API 
Через JSON API или POS API при запросах можно отключить уведомления вебхуков в контексте данного запроса.
Для этого нужно указать заголовок X-Lognex-WebHook-Disable с произвольным значением.
```
Требуется такой параметр для функций ms.GET/POST/... для передачи в запросе данного заголовка (X-Lognex-WebHook-Disable с произвольным значением).

Могу и сам сделать пр с такими правками, вопрос как лучше передавать такое в функции. Например, `ms.GET("...", { ..., disableWebhook: true }`

P.S. нашёл способ передать этот заголовок: `ms.PUT("entity/productFolder/" + id, category, null, { headers: { "X-Lognex-WebHook-Disable" : "1" } });`. Может, теперь и не очень актуально, но всё равно документированная возможность была бы полезна

**Comment by wmakeev** [comment]
Спасибо. Да, документацию надо дополнить. Обновлю.
Конечно, не очень удобно так писать каждый раз. Я думаю над тем, как сократить такую запись, при этом не вводя дополнительных сущностей.

И, кстати, `ms.PUT("entity/productFolder/" + id, ...`, я бы написал как `ms.PUT(["entity/productFolder", id], ...`, удобнее когда нужно составить url из нескольких частей.

**Comment by wmakeev** [comment]
Дополнил документацию. Возможно, стало более понятно.
