### ISSUE TITLE
Интеграция Мой склад и Амо

### ISSUE THREAD

**Issue by larionov-a** [wmakeev/moysklad#9]
Здравствуйте!
Мне нужно разработать интеграцию между АмоCRM и моим складом.
Сможете помочь в этом вопросе?
Моя почта a.larionov@yagerdev.ru

**Comment by wmakeev** [comment]
Извиняюсь, не заметил ваш ишью. Вам лучше обратиться в [группу разработчиков МойСклад](https://t.me/moyskladapi) в Телеграм.
